### ISSUE TITLE
[Bug] Interference with loading of images

### ISSUE THREAD

**Issue by Jugom** [BleedingBD/plugin-RemoveChatButtons#23]
RemoveChatButtons prevents images from loading when they are more than once per post. 

If someone posts a single picture. you can click it to open and it shows up as expected. But if there are multiple pictures in the same post, when you click it, the image never loads up.

I have both disabled/enabled all my plugins and but this one to confirm this is the only culprit.

Steps to reproduce:
1.  Upload a picture.
2. Upload 2 or more pictures in the single message.
3. Try opening the pictures while having the plugin enabled/disable to see the change in behavior.

**Comment by Jugom** [comment]
Sorry. should have checked deeper before posting. 
This is already mentioned in #20 and it gets fixed with #21

**Comment by IAmToastyGhost** [comment]
This is not fixed for me in version 1.6.0 of the plugin, but I did see that the settings "Remove Boost Bar" and "Remove Invite Button" in the Channel list section are what cause it [here](https://github.com/BleedingBD/plugin-RemoveChatButtons/issues/20#issuecomment-2191475184). I have disabled those as a workaround.

**Comment by jetblackrx89** [comment]
Same here -- this plugin is blocking the ability to click on individual images if they are in a collage / multiple images in one message. Using 1.6.0 as well.
